// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dima.proto
#ifndef GRPC_dima_2eproto__INCLUDED
#define GRPC_dima_2eproto__INCLUDED

#include "dima.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace birdy_grpc {

class ModelEndpoint final {
 public:
  static constexpr char const* service_full_name() {
    return "birdy_grpc.ModelEndpoint";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::birdy_grpc::RecognizeBirdResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>> AsyncRecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>>(AsyncRecognizeBirdByPhotoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>> PrepareAsyncRecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>>(PrepareAsyncRecognizeBirdByPhotoRaw(context, request, cq));
    }
    virtual ::grpc::Status RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::birdy_grpc::RecognizeBirdResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>> AsyncRecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>>(AsyncRecognizeBirdBySoundRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>> PrepareAsyncRecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>>(PrepareAsyncRecognizeBirdBySoundRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>* AsyncRecognizeBirdByPhotoRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>* PrepareAsyncRecognizeBirdByPhotoRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>* AsyncRecognizeBirdBySoundRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::birdy_grpc::RecognizeBirdResponse>* PrepareAsyncRecognizeBirdBySoundRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::birdy_grpc::RecognizeBirdResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>> AsyncRecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>>(AsyncRecognizeBirdByPhotoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>> PrepareAsyncRecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>>(PrepareAsyncRecognizeBirdByPhotoRaw(context, request, cq));
    }
    ::grpc::Status RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::birdy_grpc::RecognizeBirdResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>> AsyncRecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>>(AsyncRecognizeBirdBySoundRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>> PrepareAsyncRecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>>(PrepareAsyncRecognizeBirdBySoundRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) override;
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecognizeBirdByPhoto(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) override;
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RecognizeBirdBySound(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RecognizeBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>* AsyncRecognizeBirdByPhotoRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>* PrepareAsyncRecognizeBirdByPhotoRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>* AsyncRecognizeBirdBySoundRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::birdy_grpc::RecognizeBirdResponse>* PrepareAsyncRecognizeBirdBySoundRaw(::grpc::ClientContext* context, const ::birdy_grpc::RecognizeBirdRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RecognizeBirdByPhoto_;
    const ::grpc::internal::RpcMethod rpcmethod_RecognizeBirdBySound_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response);
    virtual ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecognizeBirdByPhoto() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBirdByPhoto(::grpc::ServerContext* context, ::birdy_grpc::RecognizeBirdRequest* request, ::grpc::ServerAsyncResponseWriter< ::birdy_grpc::RecognizeBirdResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecognizeBirdBySound() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBirdBySound(::grpc::ServerContext* context, ::birdy_grpc::RecognizeBirdRequest* request, ::grpc::ServerAsyncResponseWriter< ::birdy_grpc::RecognizeBirdResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RecognizeBirdByPhoto<WithAsyncMethod_RecognizeBirdBySound<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RecognizeBirdByPhoto() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response) { return this->RecognizeBirdByPhoto(context, request, response); }));}
    void SetMessageAllocatorFor_RecognizeBirdByPhoto(
        ::grpc::experimental::MessageAllocator< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecognizeBirdByPhoto(
      ::grpc::CallbackServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecognizeBirdByPhoto(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RecognizeBirdBySound() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::birdy_grpc::RecognizeBirdRequest* request, ::birdy_grpc::RecognizeBirdResponse* response) { return this->RecognizeBirdBySound(context, request, response); }));}
    void SetMessageAllocatorFor_RecognizeBirdBySound(
        ::grpc::experimental::MessageAllocator< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecognizeBirdBySound(
      ::grpc::CallbackServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecognizeBirdBySound(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RecognizeBirdByPhoto<ExperimentalWithCallbackMethod_RecognizeBirdBySound<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RecognizeBirdByPhoto<ExperimentalWithCallbackMethod_RecognizeBirdBySound<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecognizeBirdByPhoto() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecognizeBirdBySound() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecognizeBirdByPhoto() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBirdByPhoto(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecognizeBirdBySound() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBirdBySound(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RecognizeBirdByPhoto() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecognizeBirdByPhoto(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecognizeBirdByPhoto(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecognizeBirdByPhoto(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RecognizeBirdBySound() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecognizeBirdBySound(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RecognizeBirdBySound(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RecognizeBirdBySound(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecognizeBirdByPhoto : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecognizeBirdByPhoto() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>* streamer) {
                       return this->StreamedRecognizeBirdByPhoto(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecognizeBirdByPhoto() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecognizeBirdByPhoto(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognizeBirdByPhoto(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::birdy_grpc::RecognizeBirdRequest,::birdy_grpc::RecognizeBirdResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecognizeBirdBySound : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecognizeBirdBySound() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::birdy_grpc::RecognizeBirdRequest, ::birdy_grpc::RecognizeBirdResponse>* streamer) {
                       return this->StreamedRecognizeBirdBySound(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecognizeBirdBySound() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecognizeBirdBySound(::grpc::ServerContext* /*context*/, const ::birdy_grpc::RecognizeBirdRequest* /*request*/, ::birdy_grpc::RecognizeBirdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognizeBirdBySound(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::birdy_grpc::RecognizeBirdRequest,::birdy_grpc::RecognizeBirdResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RecognizeBirdByPhoto<WithStreamedUnaryMethod_RecognizeBirdBySound<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RecognizeBirdByPhoto<WithStreamedUnaryMethod_RecognizeBirdBySound<Service > > StreamedService;
};

}  // namespace birdy_grpc


#endif  // GRPC_dima_2eproto__INCLUDED
