// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: birdy.proto

#include "../protobuf/birdy.pb.h"
#include "birdy.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace birdy_grpc {

static const char* MainEndpoint_method_names[] = {
  "/birdy_grpc.MainEndpoint/RegisterUser",
  "/birdy_grpc.MainEndpoint/LoginUser",
  "/birdy_grpc.MainEndpoint/FindBird",
};

std::unique_ptr< MainEndpoint::Stub> MainEndpoint::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MainEndpoint::Stub> stub(new MainEndpoint::Stub(channel));
  return stub;
}

MainEndpoint::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RegisterUser_(MainEndpoint_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoginUser_(MainEndpoint_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindBird_(MainEndpoint_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MainEndpoint::Stub::RegisterUser(::grpc::ClientContext* context, const ::birdy_grpc::RegistrationRequest& request, ::birdy_grpc::RegistrationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RegisterUser_, context, request, response);
}

void MainEndpoint::Stub::experimental_async::RegisterUser(::grpc::ClientContext* context, const ::birdy_grpc::RegistrationRequest* request, ::birdy_grpc::RegistrationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::RegisterUser(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RegistrationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::RegisterUser(::grpc::ClientContext* context, const ::birdy_grpc::RegistrationRequest* request, ::birdy_grpc::RegistrationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, reactor);
}

void MainEndpoint::Stub::experimental_async::RegisterUser(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::RegistrationResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::RegistrationResponse>* MainEndpoint::Stub::AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::birdy_grpc::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::RegistrationResponse>::Create(channel_.get(), cq, rpcmethod_RegisterUser_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::RegistrationResponse>* MainEndpoint::Stub::PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::birdy_grpc::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::RegistrationResponse>::Create(channel_.get(), cq, rpcmethod_RegisterUser_, context, request, false);
}

::grpc::Status MainEndpoint::Stub::LoginUser(::grpc::ClientContext* context, const ::birdy_grpc::LoginRequest& request, ::birdy_grpc::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_LoginUser_, context, request, response);
}

void MainEndpoint::Stub::experimental_async::LoginUser(::grpc::ClientContext* context, const ::birdy_grpc::LoginRequest* request, ::birdy_grpc::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LoginUser_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::LoginUser(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_LoginUser_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::LoginUser(::grpc::ClientContext* context, const ::birdy_grpc::LoginRequest* request, ::birdy_grpc::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LoginUser_, context, request, response, reactor);
}

void MainEndpoint::Stub::experimental_async::LoginUser(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_LoginUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::LoginResponse>* MainEndpoint::Stub::AsyncLoginUserRaw(::grpc::ClientContext* context, const ::birdy_grpc::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::LoginResponse>::Create(channel_.get(), cq, rpcmethod_LoginUser_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::LoginResponse>* MainEndpoint::Stub::PrepareAsyncLoginUserRaw(::grpc::ClientContext* context, const ::birdy_grpc::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::LoginResponse>::Create(channel_.get(), cq, rpcmethod_LoginUser_, context, request, false);
}

::grpc::Status MainEndpoint::Stub::FindBird(::grpc::ClientContext* context, const ::birdy_grpc::FindBirdRequest& request, ::birdy_grpc::FindBirdResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_FindBird_, context, request, response);
}

void MainEndpoint::Stub::experimental_async::FindBird(::grpc::ClientContext* context, const ::birdy_grpc::FindBirdRequest* request, ::birdy_grpc::FindBirdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FindBird_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::FindBird(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::FindBirdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FindBird_, context, request, response, std::move(f));
}

void MainEndpoint::Stub::experimental_async::FindBird(::grpc::ClientContext* context, const ::birdy_grpc::FindBirdRequest* request, ::birdy_grpc::FindBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FindBird_, context, request, response, reactor);
}

void MainEndpoint::Stub::experimental_async::FindBird(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::birdy_grpc::FindBirdResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FindBird_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::FindBirdResponse>* MainEndpoint::Stub::AsyncFindBirdRaw(::grpc::ClientContext* context, const ::birdy_grpc::FindBirdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::FindBirdResponse>::Create(channel_.get(), cq, rpcmethod_FindBird_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::birdy_grpc::FindBirdResponse>* MainEndpoint::Stub::PrepareAsyncFindBirdRaw(::grpc::ClientContext* context, const ::birdy_grpc::FindBirdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::birdy_grpc::FindBirdResponse>::Create(channel_.get(), cq, rpcmethod_FindBird_, context, request, false);
}

MainEndpoint::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MainEndpoint_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MainEndpoint::Service, ::birdy_grpc::RegistrationRequest, ::birdy_grpc::RegistrationResponse>(
          [](MainEndpoint::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::birdy_grpc::RegistrationRequest* req,
             ::birdy_grpc::RegistrationResponse* resp) {
               return service->RegisterUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MainEndpoint_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MainEndpoint::Service, ::birdy_grpc::LoginRequest, ::birdy_grpc::LoginResponse>(
          [](MainEndpoint::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::birdy_grpc::LoginRequest* req,
             ::birdy_grpc::LoginResponse* resp) {
               return service->LoginUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MainEndpoint_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MainEndpoint::Service, ::birdy_grpc::FindBirdRequest, ::birdy_grpc::FindBirdResponse>(
          [](MainEndpoint::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::birdy_grpc::FindBirdRequest* req,
             ::birdy_grpc::FindBirdResponse* resp) {
               return service->FindBird(ctx, req, resp);
             }, this)));
}

MainEndpoint::Service::~Service() {
}

::grpc::Status MainEndpoint::Service::RegisterUser(::grpc::ServerContext* context, const ::birdy_grpc::RegistrationRequest* request, ::birdy_grpc::RegistrationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MainEndpoint::Service::LoginUser(::grpc::ServerContext* context, const ::birdy_grpc::LoginRequest* request, ::birdy_grpc::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MainEndpoint::Service::FindBird(::grpc::ServerContext* context, const ::birdy_grpc::FindBirdRequest* request, ::birdy_grpc::FindBirdResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace birdy_grpc

